//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Skeleton.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SKELETTYPE                  129
#define IDD_DIALOG_SELECTSIZE           130
#define IDD_DIALOG_SELECTTHRESHOLD      131
#define IDC_FILTERSIZE                  1000
#define IDC_THRESHOLD                   1001
#define IDC_RADIO_AES                   1002
#define IDC_RADIO_DES                   1003
#define ID_MENUITEM_GETBCANNELS         32771
#define ID_MENUITEM_GETSMOOTHIMAGE      32772
#define ID_MENUITEM_GETTHRESHOLDIMAGEOSTU 32773
#define ID_MENUITEM_GETTHRESHOLDIMAGEMANNAL 32774
#define ID_MENUITEM_GETTHINIMAGE        32775
#define ID_MENUITEM_GETTHINIMAGEZHANG   32776
#define ID_MENUITEM_GETTHINIMAGEROSEENFELD 32777
#define ID_MENUITEM_GETGRAYIMAGE        32778
#define ID_MENUITEM_GETTHINIMAGEDISTANCE 32779
#define ID_MENUITEM_ROOTGETTHRESHOLDIMAGEOSTU 32780
#define ID_MENUITEM_ROOTGETTHRESHOLDIMAGEMANNAL 32781
#define ID_MENUITEM_GETISOLATEPOINT     32782
#define ID_MENUITEM_COMPLETEISOLATE     32783
#define ID_MENUITEM_GETENDPOINT         32784
#define ID_MENUITEM_COMPLETEEND         32785
#define ID_MENUITEM_GETBRACH            32787
#define ID_MENUITEM_CALBRACHDATA        32788
#define ID_MENUITEM_ALL                 32791
#define ID_MENUITEM_COMPLETEMANNAL      32792
#define ID_MENUITEM_SAVEIMAGE           32793
#define ID_MENUITEM32795                32795
#define ID_MENUITEM_SOYBEANGETGRAYIMAGE 32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
